[package]
name = "docx-mcpd"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Docx MCP daemon."
readme = "../../../README.md"
keywords = ["docx", "mcp", "server"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
clap.workspace = true
tokio.workspace = true
rmcp.workspace = true
surrealdb.workspace = true

docx-core = { path = "../../lib/docx-core" }
docx-store = { path = "../../lib/docx-store" }
docx-mcp = { path = "../../lib/docx-mcp" }
docx-ingest = { path = "../../lib/docx-ingest" }

[lints]
workspace = true
